### ISSUE TITLE
Panorama TG doesn't tile new group frames

### ISSUE THREAD

**Issue by suhr** [projectdelphai/panorama-tab-groups#1]

**Comment by projectdelphai** [comment]
Working on this issue and I should have it done by the end of the weekend hopefully

**Comment by vaxul** [comment]
@projectdelphai are you share your development before the merge? I'd liked to see what's your intend to this issue.

**Comment by projectdelphai** [comment]
Of course, now that you're an active contributor, I'll stop merging straight to master and I'll be doing things similar to how I did the backup restore fix pull request. I'll make the pull request, try to have someone approve it then I'll merge. 

Also I realize I'm doing something slight different than @suhr might be requesting. I have a new mode called tiling where all groups (and any new created groups) are automatically placed on a grid evenly split. In free-form mode, having a new group be created in open space is still something I'm not sure how to fix yet.

For tiling, I just grab all the groups, calculate how to divide the screen evenly then resize each group to fit in the screen.

**Comment by vaxul** [comment]
Cool, can't wait to see it. 

> For tiling, I just grab all the groups, calculate how to divide the screen evenly then resize each group to fit in the screen.

This sound for a perfect scenario for CSS Grid.
https://github.com/vaxul/panorama-tab-groups/tree/test/grid
This is an old test branch. Far from perfect. I might do it differently today.

**Comment by projectdelphai** [comment]
I realize this might also help with #72 although it won't look as polished just yet. But easy enough to code up a quick example

**Comment by vaxul** [comment]
Yup. This is something I have on my personal roadmap. 
I think it might be a good idea if we could chat about things like this. I send you a mail, as soon I'm able to do it properly.
