### ISSUE TITLE
Increase group selection area for movement

### ISSUE THREAD

**Issue by hollyroberts** [projectdelphai/panorama-tab-groups#10]
Right now you can only move groups by selecting the bar at the top. This is often fiddly as you need to select the middle top section to avoid the group name and group close section. Often groups contain tons of blank space (below tabs and to the right). It would be create if this area would also allow us to move the group using the mouse.

**Comment by projectdelphai** [comment]
Shouldn't be too hard but I probably won't get to it until later :) Mostly working on context menus right now (closing groups and sending tabs to groups) which will probably take a couple days to fully flesh out.

**Comment by projectdelphai** [comment]
There was a bug where you stopped being able to move individual tabs since the event would bubble to the parent. Fixed in latest commit.
