### ISSUE TITLE
after a firefox crash all tabs and groups are lost

### ISSUE THREAD

**Issue by pan64** [projectdelphai/panorama-tab-groups#103]
I was typing some text in a form (inside firefox) and suddenly the browser crashed. When I restarted it there were no tabs, no groups just the initial empty page. So actually everything is lost.
I cannot restore the previous state.

**Comment by vaxul** [comment]
Do you tried to click the Panorama Tab Group button?
You could look into the addon settings for PTG and see if still tabs exists in the statistic section and then try to backup from the settings. The fresh star Firefox ans restore the backup. 

Best regards

**Comment by projectdelphai** [comment]
Tab Groups (and tabs) are stored in your local session. Afaik, if your firefox crashed and your session was not recovered, you won't be able to get your tabs back. As vaxul said, Firefox issue, not PTG issue since we work with existing tabs. Crashes removes those :(

**Comment by vaxul** [comment]
Since I used the beta channel of Firefox, I saw a lot of crashes but only a tiny margin of them totally destroyed the session. Sometimes a simple click on the PTG icon was enough for restoring.

**Comment by pan64** [comment]
This is Firefox Quantum 60.6.1esr on debian stretch (if that counts). I clicked on the Panorama Tab Group button but that page was empty too. Statistic (number of tabs) started again from beginning.

**Comment by projectdelphai** [comment]
Yep, sounds like it's a firefox losing the session problem. I was recently reading a thread about how you can try and use [this addon](https://addons.mozilla.org/en-US/firefox/addon/tab-session-manager/) to autosave your session which might help but I haven't checked if it works.

**Comment by pan64** [comment]
ok, thanks.
