### ISSUE TITLE
Show tabs as a text list

### ISSUE THREAD

**Issue by Gnustier** [projectdelphai/panorama-tab-groups#11]
Show tabs as a text list, without thumbnails, in order to show more item and make fast response when toggle panorama view.
And change the font-size and line-height of tab-list, using the CSS format.

**Comment by projectdelphai** [comment]
This will be low priority since at that point, you might as well go with some of that more tree tab addons. I'm going more for making it compatible with the legacy addon before adding new features like that. just fyi
