### ISSUE TITLE
Tab group numbering

### ISSUE THREAD

**Issue by GeneDot3** [projectdelphai/panorama-tab-groups#112]
Following my recent restore attempt I see that the groups are now numbered, this is good. However, if you delete a group there is no way to make a replacement tab with the same number. This would be a good feature to keep things in order along with a method to re-number the tabs.

I know I just sent in 3 items and I know you guys are busy, but I would like to thank you for all your hard work!  Thanks!
Gene.

**Comment by jmooo** [comment]
So is there no way to reorder tab groups? Dragging them around the Panorama View doesn't seem to do anything with regards to cycling through the groups with option+W

**Comment by vaxul** [comment]
@jmooo

Currently not. This is something that might be able with other tab group managing views in the future.

**Comment by projectdelphai** [comment]
No way to reorder currently. Thinking about either moving all group ID's down 1 to cover the missing id (which would be the easiest way). Also a possibility to rename group ids MAYBE but it would be hard and lower on the list.

**Comment by projectdelphai** [comment]
fixed this issue in latest commit. will push release within week
