### ISSUE TITLE
Impossible to clear/remove shortcut key

### ISSUE THREAD

**Issue by SylwesterZarebski** [projectdelphai/panorama-tab-groups#113]
### Current behaviour:
Now it looks like it is not possible to clear/remove shortcut key.

### What i would like:
Ability to remove shortcut.

This problem is mentioned in comment https://github.com/projectdelphai/panorama-tab-groups/issues/6#issuecomment-446075359 and no reaction is since almost half year.

**Comment by vaxul** [comment]
It seem, that @projectdelphai hasn't a lot of spare time for the project - and that is okay. I myself haven't much time too. Are you able to contribute to the feature request by yourself?

We should:
- add button to each shortcut to remove this option
- add a button or multiple to restore a single or all shortcuts

**Comment by SylwesterZarebski** [comment]
I'm afraid i do not have any knowledge how to build extensions for Firefox.

**Comment by vaxul** [comment]
The wished behaviour isn't possible with nativ API.
https://bugzilla.mozilla.org/show_bug.cgi?id=1475043

I could think about a workaround like a check for an own disabled-state on shortcut command. This would prevent the command from doing anything, but I'm not sure, if it's prevents a conflict with other extension shortcuts.

**Comment by vaxul** [comment]
@SylwesterZarebski 
You might be able to help test this feature?

First of all, backup your PTG session in the addons options dialog:
1. open Firefox
1. enter "about:addons" in the URL bar
1. click "Panorama Tab Groups"
1. beneath the section "Backup" click on the button "Export".

Afterwards, disable your current PTG addons temporary:
1. open Firefox
1. enter "about:addons" in the URL bar
1. click on "disable" within the section "Panorama Tab Groups"

To install develop version of PTG temporarily:
1. goto https://github.com/vaxul/panorama-tab-groups/tree/feature/113_allow_removal_of_shortcuts
1. click on "Clone or Download" and then "Download Zip"
1. Unzip the downloaded package in your preferred location
1. open Firefox
1. enter "about:debugging" in the URL bar
1. click "Load Temporary Add-on"
1. open the directory of the unzipped PTG develop version and select any file inside the extension.
([see this doc](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Temporary_Installation_in_Firefox))

**Comment by SylwesterZarebski** [comment]
I'll try, thanks.
