### ISSUE TITLE
I think it would be better to place the bar with the + mark on the up side.

### ISSUE THREAD

**Issue by GitHubro5** [projectdelphai/panorama-tab-groups#13]
Hello.
First, thank you in advance for your efforts.

For more information, please see the link below.
[Here ](https://github.com/photodiode/panorama-view/issues/51)is a link to what I have already contacted the original creator.
Unfortunately, there is no original author's answer or any updates yet.

**Comment by projectdelphai** [comment]
This is done and committed. It'll be with the 0.8.5 release
