### ISSUE TITLE
feature request: title instead of URL of tab

### ISSUE THREAD

**Issue by LukasAV** [projectdelphai/panorama-tab-groups#136]
Hi,
I think it would be very practical if you could display the title of the tab instead of the URL at the bottom of each tab thumbnail.
At the end of the day I have at least twenty tabs with almoust the same thumbnail saying 'stackoverflow.com/...' which does not really help finding the needed tab faster

**Comment by projectdelphai** [comment]
Already displays tab names instead of URL for me
