### ISSUE TITLE
Restoring from a backup causes all tabs to be in one invisible group

### ISSUE THREAD

**Issue by hjklqw** [projectdelphai/panorama-tab-groups#143]
(Using Firefox 68.0.2)

After a recent crash, I attempted to restore groups from a backup saved from the plugin's options menu. However, all 42 tabs I had were on the same tabbar, meaning they were all in one group--and worse is that when I opened the Panorama view, there are no groups at all; those 42 tabs are nowhere to be seen for me to be able to sort them in any way. They only came back (in one group) after I restarted the browser, and I then had to sort them again.

A few minutes ago, this happened _again_, and the restore function yet again just plops everything into the same tabbar with zero tabs visible in Panorama view. What I do notice though is that group indices have increased from last time--meaning, those missing groups probably do exist somewhere, just not in a place where I can see or do anything with them.

Am I missing something or misunderstanding how restoration is supposed to work? How do I reset the group indices, or better yet, have my groups be restored with the backup?

**Comment by vaxul** [comment]
@hjklqw
This is fixed in the current master. If you can, try to disable your version temporary and temporary install the master.

**Comment by vaxul** [comment]
First, disable your current PTG addons temporary:
1. open Firefox
1. enter "about:addons" in the URL bar
1. click on "disable" within the section "Panorama Tab Groups"

To install develop version of PTG temporarily:
1. goto https://github.com/projectdelphai/panorama-tab-groups
1. click on "Clone or Download" and then "Download Zip"
1. Unzip the downloaded package in your preferred location
1. open Firefox
1. enter "about:debugging" in the URL bar
1. click "Load Temporary Add-on"
1. open the directory of the unzipped PTG develop version and select the manifest.json file inside the extension.
([see this doc](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Temporary_Installation_in_Firefox))

**Comment by udovdh** [comment]
Will this also restore the tabgroups and not just the tabs?
