### ISSUE TITLE
Feature Request:  A button to take me back to an "all tabs" view. 

### ISSUE THREAD

**Issue by sBrecht** [projectdelphai/panorama-tab-groups#153]
I occasionally bookmark all my tabs as a "session backup" just due to FireFox's session restore being flaky sometimes.   As much as I'm loving Tab Groups I haven't found a way to select all tabs so I can make a backup.  An option, even hidden somewhere to show all tabs would be helpful.   Thanks for the great work on this project.

**Comment by modomario** [comment]
Isn't this what the backup function in the addon's settings does?

**Comment by projectdelphai** [comment]
Yep! There's a backup functionality already in the settings. Closed
