### ISSUE TITLE
Panorama TG accidentily hides tabs

### ISSUE THREAD

**Issue by suhr** [projectdelphai/panorama-tab-groups#16]
How to reproduce:

1. Open some tabs in a private window
2. Switch to a non-private window
3. Almost all tabs in the private window are hidden

Note, that this doesn't happen all the time.

**Comment by projectdelphai** [comment]
I can't reproduce this error :(

Until I can get this to happen, I would say try the following steps:

    1. Go to about:profiles and create a new profile
    1. Under your new profile, click the option to "Launch profile in a new browser"
    1. Download the panorama-view to your computer
    1. Go to about:debugging and click "Load Temporary Add-on"
    1. Load the manifest.json file in the src folder from this project

You can open debugging there and see the logs too when you you reproduce the error and see if you can figure out what you need to do break it so I can try and fix it.

**Comment by projectdelphai** [comment]
Not reproduced and no response from caller
