### ISSUE TITLE
Tab Groups view does not open anymore

### ISSUE THREAD

**Issue by PalminX** [projectdelphai/panorama-tab-groups#168]
Today, all of a sudden, the "Panorama Tab Groups" button stopped working altogether. That means pressing the button does not do anything, it doesn't open a new tab and it doesn't show the tab groups view.

This is using FF 70.0 (64-Bit) on Windows 10, with the following additional add-ons installed:
Open Tabs Next to Current	2.0.12	
Panorama Tab Groups	0.8.9	
Tab Session Manager	5.1.0	
uBlock Origin	1.23.0	

I don't know why it stopped working, maybe due to an update to FF 70?
Is there anything I can do to debug this?

**Comment by Velociraptor85** [comment]
same here on 
FF 60.2.2esr (64-Bit)
with PTG 0.8.9

**Comment by projectdelphai** [comment]
Just updated to FF 70 and trying now. @Velociraptor85 I'm pretty sure FF 60 ESR isn't compatible due to new API changes. Updating will fix that issue.

**Comment by projectdelphai** [comment]
Seems to work for me. I have two more machines at home I'll check after work but FF 70 doesn't seem to be the problem. Go to about:debugging and open the console for PTG and see if there are any errors when you open up Firefox and press the icon. I can give better directions when I get home. I'm also going to see if I have time this weekend to *finally* bundle the new version of PTG and some bug fixes there might help you out.

**Comment by PalminX** [comment]
I managed to get it to work again by disabling PTG, restarting FF and then re-enabling it.
My previous groups were lost though

**Comment by projectdelphai** [comment]
not reproducible. Should be easier to debug once I get more logging in.
