### ISSUE TITLE
All stacked

### ISSUE THREAD

**Issue by krzysztof113** [projectdelphai/panorama-tab-groups#171]
Last version made all groups look like this. Nothing is clickable. Had to install previous version to get to my tabs.
![Zrzut ekranu z 2019-11-04 10-26-14](https://user-images.githubusercontent.com/11329331/68110729-d07bf680-feed-11e9-8625-50e1eaf498f9.png)

**Comment by projectdelphai** [comment]
Duplicate of #169

**Comment by projectdelphai** [comment]
Reupdate tho, should be fixed.
