### ISSUE TITLE
Giant Red Badge

### ISSUE THREAD

**Issue by pwd-github** [projectdelphai/panorama-tab-groups#174]
I have no idea what it is and there's no option to remove it.

I have a giant number five on mine. I only have two tab groups, so I have no idea what it's even for.

**Comment by sBrecht** [comment]
I would also like an option to remove the red number of groups indicator.  I don't mind the feature but would like to also be able to turn it off.  It shows up as a Red indicator which usually means "Pending notifications" or something similar.  A couple times today already I've mistaken it for incoming email counts.  Keep up the great work... Panorama has completely changed the way I manage tabs.

**Comment by anghelos** [comment]
This also appeared on mine today, and I'd like to remove it.

**Comment by bakkerthehacker** [comment]
Duplicate of #170
