### ISSUE TITLE
Enabling Panorama View in multiple windows gets out of sync

### ISSUE THREAD

**Issue by PalminX** [projectdelphai/panorama-tab-groups#176]
I think this is a new issue with the recent updates:

- Have two windows open with different tab groups
- In one window, press the PTG button to display the Panorama View
  - Both windows switch to Panorama View
  - This is already not quite expected
- Select one tab in the first window
  - the first window switches to that tab (this is expected)
  - the second window stays on the Panorama View
- Pressing the PTG button in either window now toggles the view, but they are out of sync (i.e. one window always shows the current tab, the other window shows the Panorama View)

**Comment by projectdelphai** [comment]
Have you tried with the latest 0.8.11 update? Someone else was complaining about a similar issue but said the latest update fixed it. Just want to see if it fixed yours too.

**Comment by aroskuski** [comment]
For what it's worth, I saw the same issue with 0.8.10, but it seems to be fixed with 0.8.11.

**Comment by PalminX** [comment]
Thanks. cannot reproduce in 0.8.11, closing
