### ISSUE TITLE
List tab groups in right-click menu of toolbar button

### ISSUE THREAD

**Issue by quassy** [projectdelphai/panorama-tab-groups#179]
When right-clicking the Panorama button in the toolbar, it'd be nice to list all open tab groups to be able to quickly switch between them without having to go through the actual Panorama view.

**Comment by vaxul** [comment]
Sounds like you would like a feature like #131

**Comment by quassy** [comment]
Yes you are right, I didn't see that one so this is a duplicate, although I would be happy with something simpler (similar to the all tabs menu behind the arrow down button in the tab bar).
