### ISSUE TITLE
Not effective

### ISSUE THREAD

**Issue by grahamperrin** [projectdelphai/panorama-tab-groups#18]
Clicking the icon in the toolbar, Ctrl+Shift+F; neither action has any effect. 

Waterfox 56.2.3.

**Comment by erakli** [comment]
Possibly fixed in PR #33

**Comment by projectdelphai** [comment]
I experienced this the other day and restarting my browser seemed to fix it. But I haven't been able to reproduce it or get any logs as to why this issue happened. Hopefully #33 fixes it, but we'll see

**Comment by SainteCelery** [comment]
I have the same issue on Waterfox. No tabs auto-populate to a group. Clicking the toolbar icon takes me to a blank page with three icons on the side, which are supposed to provide functionality. Clicking them does nothing. The key commands do not produce anything. Changing them to different commands and "updating" them resets them back to the original commands. Clicking "import" never produces a window to actually choose a session to import. Basically, the only thing that works is clicking the toolbar icon to go to the blank page. Is this Waterfox specific? macOS Mojave specific? Interference from other add-ons? Please, advise; I really want to use this. Thanks.

**Comment by projectdelphai** [comment]
I have some free time today so I'll download Waterfox and take a look at it

**Comment by projectdelphai** [comment]
Alright so I looked into this and unfortunately, it's a pretty simple answer. The latest waterfox is on Waterfox 56 but tab hiding (the basis for this extension) wasn't implemented properly until Firefox 60 so this extensions won't work with Waterfox

**Comment by grahamperrin** [comment]
@projectdelphai thanks, can you add a `strict_min_version` to the manifest? And update the AMO page.
