### ISSUE TITLE
Icon shows there's a notification.

### ISSUE THREAD

**Issue by forestrf** [projectdelphai/panorama-tab-groups#184]
![image](https://user-images.githubusercontent.com/5580666/68404882-7d20d700-017f-11ea-8571-da1f17d3e73b.png)
I tried clicking everywhere (except reinstalling the extension) but the notification doesn't go away. It doesn't get in the way of anything, so if this is a bug, it is a minor one.

**Comment by bakkerthehacker** [comment]
Duplicate of #170

**Comment by forestrf** [comment]
Oops, sorry. Ok, I'm closing it. I also just discovered that it's the number of groups.
