### ISSUE TITLE
Groups not remembered between restarts

### ISSUE THREAD

**Issue by iansebryk** [projectdelphai/panorama-tab-groups#194]
as the title says.  running FF71.  tabs come back, but the groups do not.  how do i fix this?  seems kinda pointless to set up groups only to have them blown away every time i restart FF.  please point me in the right direction to fix this.  thx.

**Comment by vaxul** [comment]
Thanks for reporting. 
Would you please provide steps to reproduce your issue?

**Comment by iansebryk** [comment]
you bet:  click toolbar button,  create new group, drag tabs into group, click toolbar button to return to group 1, can switch between two groups and, at this point, it works beautifully.  quit FF.  restart FF.  all tabs in one main window, only 1 group (sometimes NO group, icon unresponsive).  start all over.  every.  single.  time.

this behaviour works every time regardless of whether i drag & drop the tabs from the Panorama window or if i send them there via the right-click menu option.  naming groups or not naming groups has no effect either.  the only thing i can think of that might be remotely connected is the TSM (Tab Session Manager) plugin.  i am going to test that tonight, but i don't see how; they don't talk to the same data.

**Comment by iansebryk** [comment]
so i did some testing over the holidays, and TSM does not impact the behaviour at all.  still not remembering tab groups between restarts.  :(  i'm kind of at a loss as to what to do next.

**Comment by vaxul** [comment]
Hi, thanks for the updates. As last resort you could:
- first backup you current Firefox profile with [Mozbackup](http://mozbackup.jasnapaka.com/)
- then try to refresh your Firefox (open address `about:support`, button on the top right)

**Comment by iansebryk** [comment]
i'll give that a shot.  let you know how it goes.  :)  have a Happy New Year, btw.  🎈 🎆

**Comment by iansebryk** [comment]
took me a while, but turns out nothing changes the behaviour.  new profile, newly installed plugins... same behaviour: tabs groups aren't saved between sessions.  if the information is saved to the tabs (not sure what that means... is that a special cookie??)... what settings could prevent that information from being retained or written?

**Comment by vaxul** [comment]
This sounds more like a general issue, which have nothing todo with this addon.

You should read through https://support.mozilla.org/en-US/kb/restore-previous-session for all information about Firefox session handling. Including the [configuration section](https://support.mozilla.org/en-US/kb/restore-previous-session#w_configuring-session-restore).

**Comment by iansebryk** [comment]
well. i got it fixed.  turns out you need to have Remember History and Form History turned ON.  on a sidenote, it isn't immediately apparent that the session has been restored.  your group count won't update until you click the icon or switch to another group.
