### ISSUE TITLE
Selected tab hard to see in overview (when there are many)

### ISSUE THREAD

**Issue by GeraldPfeifer** [projectdelphai/panorama-tab-groups#20]
I've got a group with some 400 tabs (don't ask ;-) and while things generally work fine,
in the overview/icon view it is often really hard to see the tab selected in that group.

There may be several ways to address this; one would be to use a thicker line around
the selected tab. (Currently it's a solid blue line, perhaps make that both thicker and dotted?)

**Comment by projectdelphai** [comment]
Pretty sure I actually implemented this a little bit ago and made the border a couple pixels bigger. Can't find the commit to prove it though, but it looks okay to me now. Not sure how I can judge what is big enough though as it's pretty subjective. Hopefully it works for you now.
