### ISSUE TITLE
Feature request: Extension icon without badge

### ISSUE THREAD

**Issue by eneko613** [projectdelphai/panorama-tab-groups#200]
I fnd annouying and a little bt ugly the red badge with a number inside, i find it non useful. Instead, there could be an option/toggle in settings or inside the extension to disable the badge and leave the extension icon clean like on the panorama view extension you are bassed on (https://github.com/photodiode/panorama-view).

**Comment by projectdelphai** [comment]
Already muted to a light grey! Just need to wait a bit for health reasons then I'll be fixing up some other issues and releasing a new release.
