### ISSUE TITLE
Import tabs from panorama view

### ISSUE THREAD

**Issue by erakli** [projectdelphai/panorama-tab-groups#23]
Is there option to import already hidden tabs from original extension?

**Comment by projectdelphai** [comment]
If you mean the very original official tab groups extension, then no I don't believe there is an official way. Someone wrote a script way back found [here](https://github.com/photodiode/panorama-view/issues/45) but I think it would probably be easier to just manually create them.

**Comment by erakli** [comment]
No, I'm not interested in legacy. I talked about panorama-view, that you forked.

**Comment by projectdelphai** [comment]
It's almost exactly the same code, so in panorama-view, you can export your tabs. And then activate panorama-tab-groups and import. as long as photodiode's import/export code works, that should just work. I haven't touched/refactored that code yet
