### ISSUE TITLE
Feature request: Ability to close tabs from panorama view

### ISSUE THREAD

**Issue by cronco** [projectdelphai/panorama-tab-groups#232]
This could either done as an x button on the individual tabs, but I can see how that's problematic if the tabs are too small.

Alternatively a context menu action would be great. Or a multi-select feature and closing all selected tabs at a time.

**Comment by tinsoldat** [comment]
Already works with middle mouse button.

**Comment by cronco** [comment]
@tinsoldat I'm on a macbook with a trackpad that doesn't have a built-in gesture for middle click

**Comment by leedoyle** [comment]
@cronco  you could probably emulate it with xdotool or similar. Not sure if that would be acceptable to you UX-wise, though...

**Comment by cronco** [comment]
This seems to have been added in a new release with an x button. Thank you!
