### ISSUE TITLE
In panorama view window, search tabs by typing

### ISSUE THREAD

**Issue by piRGoif** [projectdelphai/panorama-tab-groups#24]
In the original panorama, selecting a tab could be done using only the keyboard : open the panorama tab, type a part of the tab title, enter.
Indeed when knowing what you want to open, typing the title to select the corresponding tab is far more efficient than searching visually in the desired thumbnail. FOr example, when working with a ticket manager, you know you'll going to switch to ticket R-013842, but you have 5 tickets open and every thumbnail is almost the same as the other.

**Comment by roeyk** [comment]
Has there been any movement on this since the bug was filed?  I enjoyed this feature in pre-Quantum Firefox, where typing anything during while in Tab Groups view would shadow all the tabs open aside from the ones matching the search string.  Is there a possibility we can get that into Panorama Tab Groups too?

**Comment by vaxul** [comment]
No, nothing to highlight. 

>  Is there a possibility we can get that into Panorama Tab Groups too?

Sure, but it would require a lot of spare time.

**Comment by projectdelphai** [comment]
This is finally implemented at a base level! It's a super basic implementation, but basically what you type in the search bar in the panorama view is lowercased then compared with each tab title lowercased. The first match is selected and made the active tab (highlighted in blue).

Maybe in the future we can do something such as shadowing other tabs or something fancy but this was a lot easier and quicker to implement. Closing this ticket as fixed. A small QoL update in the future will probably be auto focusing the search bar when you type.

**Comment by spastorino** [comment]
@projectdelphai this is a very good way of implementing useful features :+1:. One suggestion, for when you rework a bit the search idea, on top of what you're saying would be nice to search for group name too, maybe even giving back the first tab.
