### ISSUE TITLE
how to switch goup use script in console?

### ISSUE THREAD

**Issue by wideweide** [projectdelphai/panorama-tab-groups#244]
then I can use it in console,or map new single keyword in  tridactyl

**Comment by bakkerthehacker** [comment]
This is possible with the code: 
`browser.runtime.sendMessage("panorama-tab-groups@example.com", "activate-next-group");`
and `browser.runtime.sendMessage("panorama-tab-groups@example.com", "activate-previous-group");`

Viewing all groups used to be possible but an [update broke this functionality](https://github.com/projectdelphai/panorama-tab-groups/issues/206) and it has not yet been restored.  currently only supports going up or down a list of groups

You can install version 0.8.11 from here: https://addons.mozilla.org/en-US/firefox/addon/panorama-tab-groups/versions/

**Comment by wideweide** [comment]
cool, it works!
`bind gd js browser.runtime.sendMessage("panorama-tab-groups@example.com", "activate-next-group");`

Expect more features, such as:
Switches to the specified name of the group
Move tab to a group
