### ISSUE TITLE
Panorama Tab Groups changes to Popup mode upon Firefox update

### ISSUE THREAD

**Issue by Cris70** [projectdelphai/panorama-tab-groups#247]
Every time Firefox is updated, Panorama Tab Groups reverts to Popup mode. I always have "Freeform" mode in preferences.
If, after updating Firefox, I go to Panorama Tab Groups' preferences, I see that Freeform is selected just as before the update; nonetheless the add-on behaves as if "Popup" was selected.
Changing to Popup and then back to Freeform fixes the problem... until the next update.

Firefox 84.0.1 on Linux (openSuse Tumbleweed) with KDE Plasma 5.20.5. 
Panorama Tab Groups is v0.8.12.

**Comment by vaxul** [comment]
🤔 this is weird. Normally the settings are not restored after an update. I asume @projectdelphai would have fixed it already, since he preferred the freeform mode in past.

**Comment by Cris70** [comment]
_Merged_ with #248
