### ISSUE TITLE
Issues since the latest Firefox or PTG update

### ISSUE THREAD

**Issue by CaptainKoons** [projectdelphai/panorama-tab-groups#248]
Hi Devs,

First of all, thank you for the great work with panorama tab groups.

Unfortunately, I discovered some issues since some days (since the latest Firefox or PTG update?).

1.	When I start Firefox PTG is always in popup mode. But when I go to the preferences menu “classic mode” is selected. I have to switch back and forth between popup and classic, to really get the freeform mode. But it only keeps it till the next closing/opening of Firefox. Then popup is selected again. This issue seems to be mostly identical to issue #247 but as I said I have this issue not only after updates but every time I start Firefox.

2.	I’m losing tabs. When switching between tab groups in classic mode I sometimes lose tabs (especially in main tab group). I’m not able to give account of this. But it seems like PTG is not saving the latest open tabs correctly und when switching to another tab group and back to the main one it reopens an older version of this group. 

3.	When I’m using popup mode and I select a tab from another tab group out of the tab tree, this tab gets opened in the current tab group instead of switching me to the tab group of the selected tab.

I’m using Firefox 84.0.2 (64-Bit), PTG 0.8.12 and Windows 10 Pro Version 2004.
If you need any further info’s, let me know. 

Sorry for my bad English, unfortunately I’m not a native speaker. But I hope you can understand my issues anyway. :-)

Thanks in advance!
CK

**Comment by Cris70** [comment]
I have all the same issues as @CaptainKoons. 
I'm going to close #247 as the bug now behaves as described in this bug. The strange thing is that I am experiencing the bug on one of my boxes but not on the other. 
On both boxes I am running linux (OpenSuse Tumbleweed) and Firefox 85.0.2 and PTG 0.8.12.
The only difference *may* be that on one of the boxes I may have had the older PTG add-on that this one is substituting. Maybe a clash with some leftover?

**Comment by Cris70** [comment]
Just finished reading bug #249: I have Facebook Container too and I believe the problem is due to the incompatibility described on bug #249.
This also explains why I'm not experiencing these problems on the other box.

**Comment by CaptainKoons** [comment]
I had Facebook container activated too. After deactivating it, the issue seems to be immediately solved. And PTG is also working way faster now.

Big thanks @Wronschien for recognizing this correlation and sharing it (issue #249)!
And also thanks @Cris70 for linking these two issues!

I will close this issue. Ways to have both extensions activated and working properly at the same time may be investigated at issue #249.
But in the meantime, I will keep Facebook container deactivated.

BR,
CK
