### ISSUE TITLE
bulk selecting tabs

### ISSUE THREAD

**Issue by leedoyle** [projectdelphai/panorama-tab-groups#25]
Please implement bulk selecting tabs. 
In the legacy past one would do it with muiltiple tab handler, but as of now, MTH and panorama tab groups don't have a way to communicate. 

I would be happy if we could bulk select tabs while in panorama view while holding ctrl or shift.

**Comment by piroor** [comment]
Firefox 63 and later supports multiselection of tabs natively. (Note that you need to activate `browser.tabs.multiselect` via `about:config` on Firefox 63.) You can collect multiselected tabs like `browser.tabs.query({ windowId: tab.id, highlighted: true })`, so I think Panorama Tab Group should move them together if there are multiselected tabs and the tab is a part of multiselection.

**Comment by piroor** [comment]
By the way, if Panorama Tab Groups provides an extra tab context menu  item like "Move Tab(s) to Group" (it will have its submenu for existing groups) via `browser.menus.create()`, it will appear in the context menu of MTH (and Tree Style Tab also) on [Firefox 64 and later](https://piro.sakura.ne.jp/latest/blosxom/mozilla/xul/2018-10-14_override-context-on-fx64.htm#topic2018-10-14_override-context-on-fx64). We don't need to do special things for integration of both addons anymore.

**Comment by BlangTech** [comment]
I'm working on the implementation of the context menu right now. I liked that feature very much in the old "Tabgroups"-Addon from Quicksaver.

**Comment by pwd-github** [comment]
Just to be clear, within the current Nightlies, there's no way to select multiple tabs from within the tab group overview screen.

**Comment by marsjaninzmarsa** [comment]
> Just to be clear, within the current Nightlies, there's no way to select multiple tabs from within the tab group overview screen.
And should be. 😉

**Comment by leedoyle** [comment]
> Just to be clear, within the current Nightlies, there's no way to select multiple tabs from within the tab group overview screen.

Yes, that's something that didn't exist in legacy Tab Groups by quicksaver.  It would be great if that was also implemented, alongside the integration piroor has been speaking about. 
Sorry, your confusion is my fault - in fact, I should have created **two issues** - one for multi selecting **while in panorama view** and one for **integration** with browser's native  tab multiselect or Multiple Tab Handler

>(Firefox 63 and later supports multiselection of tabs natively

However, the issues are closely related in that they serve the same purpose, so I'll let this issue be the way it is.

**Comment by projectdelphai** [comment]
There's not enough information to know exactly what you mean by select multiple tabs, but if I understand you correctly you can now select multiple tabs and then send to another group via the right-click context menu. There's some peculiarities about the "Send to" function that doesn't work great but it's progress. Reopen if you wanted something else.
