### ISSUE TITLE
[Feature] Grid Layout

### ISSUE THREAD

**Issue by RageYL** [projectdelphai/panorama-tab-groups#3]
Hi,

Thank you for taking over this add on ;)
I'm reposting a feature request that i opened on the previous project:

Is it possible to provide a grid layout in addition to the manual one like in the old Tab Groups ? Providing an option to arrange the groups using a css grid would already makes managing lots of groups much easier.

Thanks.

**Comment by projectdelphai** [comment]
This is something I've already been thinking about mostly because it's pretty annoying to create a new group and then have it only spawn in the far left. So having it have some sort of arrangement system/snapping to grid would be nice.

**Comment by projectdelphai** [comment]
Done with the latest tiling pull request that I just merged in. You can now switch to tiling mode.
