### ISSUE TITLE
Navigate using keyboard on panorama view

### ISSUE THREAD

**Issue by tonnydourado** [projectdelphai/panorama-tab-groups#4]
Would be nice to be able to navigate inside each tab group, and between tab groups, when on the panorama view.

**Comment by projectdelphai** [comment]
This is something that's possible. I was already thinking of having a slight border/highlight around the current active tab so you know where you are. And then switching the active tab/highlight with the arrow keys + tabbing to go to the next group might be nice.

**Comment by vaxul** [comment]
In addition it might be a help to use semantic HTML for interactive elements.

In a short test in https://github.com/vaxul/panorama-tab-groups/commit/ae6023f90cc1354e0dc5bf7494b40584714b47ab I tried to use buttons for the toolbar buttons. This alone enables keyboard usage with these.

But I have currently not an ideal idea for the tab groups and tabs. But continuing thinking on it.

**Comment by projectdelphai** [comment]
This is now done in v0.8.5, you should see it tomorrow. It's not a super polished feature, but the basics left arrow, right arrow, and enter are implemented

**Comment by projectdelphai** [comment]
nvm, it doesn't work properly on my main browser, I'll take a look into this

**Comment by projectdelphai** [comment]
This is fixed now and should be fully working in 0.8.6
