### ISSUE TITLE
Lost groups

### ISSUE THREAD

**Issue by ahmed-tea** [projectdelphai/panorama-tab-groups#40]
After last update most of my groups are disappeared

**Comment by projectdelphai** [comment]
Hm, I haven't heard of any issue with missing groups and I released that update 22 days ago (I haven't lost any groups). Is there anything you changed in that last 3 weeks that could cause this? Or is there any rhyme or reason to the groups that you lost? 

Without any more information that could give me somewhere to look, I'm afraid I'm not sure how I can fix this issue :(

**Comment by projectdelphai** [comment]
Closing because no response.
