### ISSUE TITLE
Move extension button to tabstrip

### ISSUE THREAD

**Issue by marsjaninzmarsa** [projectdelphai/panorama-tab-groups#42]
Tabstrip is natural place for tab-management addon button, where original Panoramas button was located. Since Firefox 54 we can define initial location of `browser_action` via `default_area` key, so why not restore original behavior?

**Comment by projectdelphai** [comment]
This is probably something that won't be changed mostly for two reasons:

 1. Most tabs I've seen and used keep the extension icon in the navbar. So keeping it there instead of the tabstrip keeps things consistent and doesn't confuse anyone.
 2. If people want to move the icon up to the tabstrip, it's possible to actually do that without the add-on forcing them there. You just need to right click on the top of the browser, click Customize, and then drag any extensions up to the tab strip.

**Comment by marsjaninzmarsa** [comment]
> Most tabs I've seen and used keep the extension icon in the navbar. So keeping it there instead of the tabstrip keeps things consistent and doesn't confuse anyone.

Because of the lack of API/knowledge? Maybe I'm the only one missing this:
![obraz](https://user-images.githubusercontent.com/1119575/52015976-90fa2700-24e3-11e9-8312-374151999a2c.png)
Should consistency with other extensions be more important than with original one? Why would keeping tab-management related stuff near tabs be confusing?

> If people want to move the icon up to the tabstrip, it's possible to actually do that without the add-on forcing them there.

Easy, easy, no one is trying to force anybody to anything, it's reversible - you just need to right click on the top of the browser, click Customize, and then drag any extensions down to the extension bar. 😉

Rly, I understand your arguments, but I can't agree - Panorama, in my opinion, was very well designed, and you with your fork seems to be closer to recreate that exact experience (as it's possible within current technology limits ofc) than any other, so why struggle making PTG looking decent, polite, standing properly among others, if they're going in their own directions anyway (despite not being any better)? Your goal, I think, was never to overtake users of Simple Tab Groups or Sync Tab Groups, but rather to take up orphans after Quicksaver/Tab-Groups, so why are you rejecting that heritage? 😉 We - as extension makers - after long time of analysis and evaluation by our bests in Mozilla, got access to API allowing better (contextual) positioning, why not use it? "Because nobody else uses it" is far from great as justification, especially when comes to still fresh, oftentimes poorly documented, rapidly evolving technology, based on and very similar to an older one, being mostly compatible but much more restricted. No one here was seemed to be using it because you're just the first one, you're on a virgin territory. 😅

Ofc I'm not any revived UX guru thus I'm aware of fact that it may be just my personal perversion, disparate to general preferences (so I have no intent to induce you further, especially with something so trifling), but I'm heavily convinced about it, hence I'll be grateful if you, still, leave this ticket opened, even as "wontfix", just to gather additional feedback. 🙂
