### ISSUE TITLE
Addon messages

### ISSUE THREAD

**Issue by suhr** [projectdelphai/panorama-tab-groups#5]
Gesturefy can send messages to other addons: https://github.com/Robbendebiene/Gesturefy/wiki/Send-message-to-other-addon

It would be nice to receive action messages in Panorama TG, so you could toggle panorama view with a gesture.

**Comment by projectdelphai** [comment]
@suhr I think this is possible and it looks like it's just one short function. I don't use gesturefy add-on but it looks like it's used for mouse movements right? So it seems like just adding gesture support for the keyboard shortcuts (toggle view, switch to next/previous group) are the only things that need support right?

**Comment by suhr** [comment]
> it looks like it's used for mouse movements right

Mouse gestures.

> So it seems like just adding gesture support for the keyboard shortcuts

I suppose an addon cannot simulate a keyboard shortcut. So it sends messages you can receive with [`onMessageExternal`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/onMessageExternal).

**Comment by projectdelphai** [comment]
This is now supported! The commands are "toggle-panorama-view", "activate-next-group", and "activate-previous-group". I will update the README tomorrow if you need more help.

**Comment by suhr** [comment]
Yes, this works (I expected json messages, but a plain string is probably fine too).

**Comment by projectdelphai** [comment]
Well at the end of the day, you just do a string comparison to check what command was sent to you and considering there are only three commands, it seemed like overkill to have anything other than plain strings. Glad it works out though!
