### ISSUE TITLE
Update link incorrect

### ISSUE THREAD

**Issue by cmeeren** [projectdelphai/panorama-tab-groups#68]
Installing the latest update automatically opened

https://github.com/projectdelphai/panorama-tab-groups/releases/tag/0.8.7

which doesn't exist (404)

**Comment by projectdelphai** [comment]
Fixed, thanks for letting me know :) Renamed the tag to 0.8.7 instead of V0.8.7

**Comment by vaxul** [comment]
I hope not too many users missed this quite important notes about some more major changes. 🤔
