### ISSUE TITLE
continue from original's issue #93

### ISSUE THREAD

**Issue by hong620** [projectdelphai/panorama-tab-groups#7]
heres the debug console info

> Could not map contract ID '@mozilla.org/widget/printdialog-service;1' to CID {06beec76-a183-4d9f-85dd-085f26da565a} because no implementation of the CID is registered.
Could not map contract ID '@mozilla.org/fxaccounts/push;1' to CID {1b7db999-2ecd-4abf-bb95-a726896798ca} because no implementation of the CID is registered. components.manifest:165
TypeError: can't access dead object[더 알아보기] accessible.js:128:5
Error: "Illegal URL: about:addons" backup.js:77:24
Use of nsIFile in content process is deprecated. NetUtil.jsm:266:12
[메시지에 대한 자세한 정보를 보거나 숨깁니다.] tabNodes[tabId].tab.parentNode is null tabNodes.js:118
deleteTabNode
moz-extension://9aa7fb56-c12a-4efc-a84d-039a429d0d4c/js/tabNodes.js:118:3
tabRemoved
moz-extension://9aa7fb56-c12a-4efc-a84d-039a429d0d4c/js/view.js:175:3
apply self-hosted:4553:5 applySafeWithoutClone
resource://gre/modules/ExtensionCommon.jsm:234:16
fire
resource://gre/modules/ExtensionChild.jsm:917:28
receiveMessage
resource://gre/modules/ExtensionChild.jsm:920:38
_callHandlers/<
resource://gre/modules/MessageChannel.jsm:866:17
_callHandlers
resource://gre/modules/MessageChannel.jsm:865:14
_handleMessage/deferred.promise<
resource://gre/modules/MessageChannel.jsm:940:7
_handleMessage
resource://gre/modules/MessageChannel.jsm:937:24
_handleMessage self-hosted:988:17 receiveMessage/<
resource://gre/modules/MessageChannel.jsm:208:9
forEach self-hosted:268:13 receiveMessage
resource://gre/modules/MessageChannel.jsm:201:5
TypeError: this.contentWindow is null[더 알아보기] ExtensionPageChild.jsm:191:5 

i'm not a dev and not much knowledge in coding.. so seems it's my limit.

i'll try from your fork and then see what i can do.

**Comment by hong620** [comment]
I've temporaily load your fork from debugging menu, seems it all works in same tab list same enviorments from your versions.

but no other options to use it until regist in mozilla extension sites and certificate so..

anyway i hope mozilla add more api to make advance on these like extensions, and then devs in fork that projects hope to complete new horizon with new Quantom Renderer.

**Comment by projectdelphai** [comment]
@hong620 it's available on the mozilla extension site! It's available [here](https://addons.mozilla.org/en-US/firefox/addon/panorama-tab-groups/). Let me know if that works for you!
