### ISSUE TITLE
Add a "move to group" option in tab contextual menu

### ISSUE THREAD

**Issue by piRGoif** [projectdelphai/panorama-tab-groups#71]
This would be pretty usefull, avoiding to open the panorama view, and just right click on the tab you want to move...

**Comment by projectdelphai** [comment]
Done :)

**Comment by piRGoif** [comment]
Many thanks, works like a charm ! I was stuck since some weeks with just an empty groups and all my tabs associated with none, I was able to recover everything using this magic menu entry !! Many thanks !
