### ISSUE TITLE
[Feature Request] Original "single view" mode

### ISSUE THREAD

**Issue by irvinm** [projectdelphai/panorama-tab-groups#72]
As a user with anywhere between 750-1000 tabs, I used to rely on Panorama to help me create 10-15 groups that I could organize and search effectively.  I am currently relying of TreeStyleTab to create tree hierarchies which can be collapsed to achieve a similar experience.

I see that Panorama Tab Groups has matured significantly and the progress is fantastic!  The two features that might greatly help users with a large number of tabs would be:

1. Search capabilities. - Already discussed in https://github.com/projectdelphai/panorama-tab-groups/issues/24

2. A similar implementation of the original "Single View".  The idea is that each "group" would simply have a square along the top row and as you clicked on any of those groups, the tabs from that group (alone) would be displayed in the main page area.  This has the benefits that a group with a large number of tabs can be seen much easier without having to try to move aside or resize all of the other groups.  The behavior of the tabs displayed can be the same, it is really just a different way to display all of the groups so groups with a large number of tabs can be worked with. [Obviously, search is still important here as you want to not only know if a search term is in the current group view, but also in other groups]

**Original views that were offered:**

![tab-groups](https://user-images.githubusercontent.com/979729/51929906-5733fe00-23c7-11e9-8448-9d4ba7a6a375.png)

**Original view of "single view":**

![tab-groups](https://user-images.githubusercontent.com/979729/51929971-7f236180-23c7-11e9-8d3b-13735a73c9da.jpg)

**Write-up of the ask:**

I had forgotten that I had even written-up a feature enhancement for "Simple Tab Groups" about a year ago, but found it when searching the internet.

https://github.com/Drive4ik/simple-tab-groups/issues/88

**Screenshot of proposed idea**

![36176096-841c54d6-10df-11e8-9790-3c5c1f8df892](https://user-images.githubusercontent.com/979729/51930329-4e8ff780-23c8-11e9-846f-033016e0e6f7.png)

1. Box along the top for each group with squares showing number of tabs in each (Ex: "Main" has a lot and "Programming" has far fewer)
2. Once clicking on one of the groups, simply use all of the space below and "best fill" the tabs in that space (More tabs = smaller size)
3. Show the number of tabs as number for the selected group. (Personally, I would like that number for each group somehow)
4. Allow global searching, thus highlighting the tabs in that group and the remaining groups that match the search

**Comment by vaxul** [comment]
The original view of the original Tab Group addon is something I have on my list. But I can't say for sure when I even start with this.

**Comment by irvinm** [comment]
Thank you @vaxul as I figured that might be your response.  I figure at a minimum we have a record of the ask and the behavior and if it happens it will be very welcome in the future.  Thank you again for even getting it to this point!

**Comment by Sada-Mio** [comment]
I really miss the old "single view" mode too!

Right now I have to manually expand/resize each group which is a pain dealing with many tabs.

**Comment by projectdelphai** [comment]
Is there a way to find those old icons?

**Comment by vaxul** [comment]
In the old repository. 

https://github.com/Quicksaver/Tab-Groups/tree/master/chrome/skin/common

As HighDPI desktop user I would prefer to convert them into / recreate them as SVG.

**Comment by Sada-Mio** [comment]
Single view mode of #72 still planned? Noticed this was  closed for Tiling #125 

![pano](https://user-images.githubusercontent.com/38301959/74417283-4e0fa680-4dfb-11ea-9b80-114fb0b65d37.png)

panorama-tab-groups not really usable when there are many tabs. Would love to split them up into smaller groups that can be minimize/maximized like single view mode.
