### ISSUE TITLE
Export doesn't work (clicking "Save backup" does nothing)

### ISSUE THREAD

**Issue by mgol** [projectdelphai/panorama-tab-groups#73]
Opening the extension's preferences and clicking "Save backup" does nothing. Therefore, performing a backup is impossible.

The same button in the original Panorama View extension opens a file save system dialog.

Extension 0.8.7
Firefox 65.0
macOS 10.14.3 (18D42)

**Comment by projectdelphai** [comment]
I'll check on this, I don't really use the backup feature myself (and someone else has worked on this in the past), I'm sorry I didn't miss this feature breaking. I'll go check on it when I can and see why it doesn't work.

**Comment by HGondorff** [comment]
Just wanted to say that this feature is also extremely important to me as well. If Firefox's "Restore previous session" gets unchecked, as happened to me with the v.65 update, you get the "Do you want to close all tabs" when you exit and can't exit without doing it. This causes all tab groups to be lost. Keeping a backup lets you import those tab groups back in. It's a lifesaver.

**Comment by vaxul** [comment]
In case of @HGondorff an automatic backup would be nice. But this would be a different feature.

**Comment by HGondorff** [comment]
Just want the Save Backup button to work again, please. Hope someone figures it out.

**Comment by ameerabsalam** [comment]
I've lost all my tab groups multiple times with various Tab Groups extensions over the years (including this one).  I don't have the logs/details to reproduce it, but I'd simply open up Firefox one day and find all tab groups as one huge group.

Posting this to +1 a backup/save feature fix

**Comment by projectdelphai** [comment]
Figured it out, it was extremely stupid. update incoming

**Comment by projectdelphai** [comment]
It's fixed, basically when some options were added to the options page in the shape of a <form>, there wasn't a corresponding </form> which meant that the save backup button was counted as the button for the form. And because it's not a proper form, the button didn't do anything. Closed the form properly and the button works now. Easy mistake to make and easy to fix, just hard to find :)

git bisect was particularly helpful

**Comment by mgol** [comment]
@projectdelphai Something got eaten in your comment. ;) Did you use an HTML tag? Markdown understands HTML so if you post code you need to wrap it in backticks or we won't see it.

**Comment by HGondorff** [comment]
The update is not coming through. I'm still stuck with 0.8.7. I am tempted to delete and download the new version but am afraid of losing my tabs in the process. I have tried setting the updates to default and automatic to no avail.

**Comment by projectdelphai** [comment]
@HGondorff [this link](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/Updates#Testing_Automatic_Updating) should help you out if you really can't update. That being said, have you tried clicking the little gear on the right hand side of the PTG options page? It'll allow you to automatically download the new update. Firefox only checks once a day, so that might be why your update hasn't come in yet. 

If you have tried to manually update, then there might be something else wrong.

**Comment by projectdelphai** [comment]
@mgol lol yeah i escaped the html tags so it should be good now, thanks for letting me know. Didn't realize backticks helped escape too, I just used back slashes by default and that worked too.

**Comment by HGondorff** [comment]
Ah yes, the little gear I didn't know was there :) All is well and my anxiety level has declined. My sincere gratitude for the fix!

**Comment by projectdelphai** [comment]
anytime :)

**Comment by ricardoroehe** [comment]
> Opening the extension's preferences and clicking "Save backup" does nothing. Therefore, performing a backup is impossible.

Same issue here. Noticed it only after restarting Firefox.
Also, I noted the "keyboard shortcuts" fields are empty (like the shortcuts for PTB have been removed). Maybe they could not be read from somewhere (the place where this info was stored)? 
I'm not an expert, but it seems incompatibility with some other add-on. PTG was working flawlessly before the restart.

My system:
Firefox 88.0.1 (64-bit) on Linux Mint 19.2 Cinnamon
PTG v. 0.8.12

All add-ons / addons / extensions I have here:
- Adblock Plus - free ad blocker
- All Downloader Professional
- Autofill
- Awesome Emoji Picker
- Best Proxy Switcher
- Change Case
- Chrome Remote Desktop
- Conex
- Copy Link Text
- Download Star
- DownThemAll!
- DuckDuckGo
- Emoji Cheatsheet for GitHub, Basecamp etc.
- Fess Google Bookmark Extension
- Firefox Multi-Account Containers
- Greasemonkey
- Image Search Options
- Panorama Tab Groups
- Rotate and Zoom Image
- Saka Key
- Search by Image
- Startpage
- Stylish - Custom themes for any website
- Video Downloader professional
- Video DownloadHelper
- View Image
- Wikipedia (en)
- Yahoo!
- YouTube Tooltip & Notification
- English (CA) Language Pack
- English (GB) Language Pack
