### ISSUE TITLE
Russian Translation

### ISSUE THREAD

**Issue by Neytrino-OnLine** [projectdelphai/panorama-tab-groups#74]
I am not sure how to correctly create a pull request, so i did it here...

**Comment by Neytrino-OnLine** [comment]
{
    "newGroupButton": {
        "message": "Новая группа"
    },
    "settingsButton": {
        "message": "Настройки"
    },
    "defaultGroupName": {
        "message": "Группа без названия"
    },
    "dragGroup": {
        "message": "Переместить"
    },
    "closeGroup": {
        "message": "Закрыть"
    },
    "closeGroupWarning": {
        "message": "Закрывая эту группу, вы закроете $1 вкладку$2/$3/$4 вкладки$5 вкладок в ней. Вы уверенны что хотите этого?"
/* in Russian there are 3 gradation of "tab" word: 1 tab = 1 вкладка, 2 or 3 or 4 tabs = 2/3/4 вкладки, 5 and more tabs = 5 вкладок... */
    },
    "optionKeyboardShortcuts": {
        "message": "Сочетания клавиш"
    },
    "optionKeyboardShortcutsHelpLink": {
        "message": "https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/commands#Key_combinations"
    },
    "optionKeyboardShortcutsHelpLinkText": {
        "message": "Подробности о правилах синтаксиса команд, можно найти тут."
    },
    "optionKeyboardShortcutsButtonsUpdate": {
        "message": "Задать"
    },
    "optionKeyboardShortcutsButtonsReset": {
        "message": "Сброс"
    },
    "optionKeyboardShortcutsToggle": {
        "message": "Просмотр в режиме панорамы"
    },
    "optionKeyboardShortcutsNextGroup": {
        "message": "Выбрать следующую группу вкладок"
    },
    "optionKeyboardShortcutsPreviousGroup": {
        "message": "Выбрать предыдущую группу вкладок"
    },
    "optionsTheme": {
        "message": "Тема оформления"
    },
    "optionsThemeLight": {
        "message": "светлая"
    },
    "optionsThemeDark": {
        "message": "тёмная"
    },
    "optionsToolbar": {
        "message": "Панель инструментов"
    },
    "optionsToolbarPosition": {
        "message": "Положение"
    },
    "optionsToolbarPositionTop": {
        "message": "сверху"
    },
    "optionsToolbarPositionRight": {
        "message": "справа"
    },
    "optionsToolbarPositionBottom": {
        "message": "снизу"
    },
    "optionsToolbarPositionLeft": {
        "message": "слева"
    },
    "optionsBackup": {
        "message": "Резервное копирование"
    },
    "optionsBackupImport": {
        "message": "Импорт"
    },
    "optionsBackupImportText": {
        "message": "Импортируемые резервные копии открываются в новом окне, не затрагивая уже открытые вами окна и вкладки.<br />Вы также можете импортировать резервные копии, сделанные старым расширением \"Tab Groups\"."
    },
    "optionsBackupExport": {
        "message": "Экспорт"
    },
    "optionsBackupExportText": {
        "message": "Здесь вы можете сохранить абсолютно все параметры текущей сессии, доступные в Firefox."
    },
    "optionsBackupExportButton": {
        "message": "Сохранить резервную копию"
    },
    "optionsStatistics": {
        "message": "Статистика"
    },
    "optionsStatisticsNumberOfTabs": {
        "message": "Число открытых вкладок:"
    },
    "optionsStatisticsNumberOfTabsActive": {
        "message": "Активных:"
    },
    "optionsStatisticsThumbnailCacheSize": {
        "message": "Размер кэша миниатюр:"
    }
}

**Comment by vaxul** [comment]
Hi, thanks for your contribution.

> I am not sure how to correctly create a pull request, so i did it here...
Would this help you to create a pull request?
https://github.com/projectdelphai/panorama-tab-groups/blob/master/CONTRIBUTION.md#in-general

If you need help, let me know.

**Comment by vaxul** [comment]
This isn't quite as easy as I thought. We have to declare different [Plural Rules](https://developer.mozilla.org/en-US/docs/Mozilla/Localization/Localization_and_Plurals#List_of_Plural_Rules). I'm currently looking into this.

**Comment by Neytrino-OnLine** [comment]
Where to find messages for a tab context menu items to translate?
https://cdn1.savepice.ru/uploads/2019/2/19/5d1cfb1278b9321d432b978f14c61bb6-full.png

"Send To Group" = "Переместить в группу"
"Refresh Groups" = "Обновить список групп"

**Comment by projectdelphai** [comment]
Not something that's currently implemented because I forgot to include them. will do

**Comment by projectdelphai** [comment]
Done in the next update
