### ISSUE TITLE
Another Critical Issue by Tab Group Window Handling Limitation

### ISSUE THREAD

**Issue by hong620** [projectdelphai/panorama-tab-groups#8]
https://gfycat.com/RectangularGrandioseAntbear

current Panorama view limit Tab Group Window's position to inside screen for avoid issues like unable to interact the window things.

but when you drag tab to 'Tab Group Window's Title bar', then acctually new tab group window apear upside codinate of screen.

so unable to close or drag to cleaning it.
all the buttons and dragable points are topside of each groups so.. no alternative solution for fix this.
there's no codination recorrection so even restart or re-activate extension doesn't change those 'outside condinations'

**Comment by projectdelphai** [comment]
I know about this and I agree that's it's a very critical bug that I'm working on right now. I'm thinking making a context menu so you can right click and click "Close Group". I'll let you know when this is fixed.

**Comment by projectdelphai** [comment]
Double clicking a group will now close it so you should be able to close it if it gets lost off screen. I might change these shortcuts later. But for now, this works.
