### ISSUE TITLE
Tab group moved in the panorama view goes beneath all other tab groups

### ISSUE THREAD

**Issue by dhlocker** [projectdelphai/panorama-tab-groups#85]
Version 0.8.7 - Tried to move a tab group panel to see if issue #58 still existed, but the panel then dropped beneath all existing tab group panels. It appears that the latest moved panel is moved under [all?] others. By moving the panel under which the first panel had disappeared, I was able to see the first moved panel again.

**Comment by crass** [comment]
As of current master (`ca23455e9`), I don't see this issue.  Currently, moving a group will bring it to the foreground.

**Comment by projectdelphai** [comment]
Closing as duplicate
