### ISSUE TITLE
PT-BR locale

### ISSUE THREAD

**Issue by glha** [projectdelphai/panorama-tab-groups#88]
Hey there!

I've sent a [pull request](https://github.com/projectdelphai/panorama-tab-groups/pull/87) with all strings translated to **pt-br**. They can also be used for **pt-pt** or just **pt**, as they are quite simple and can be easily understood. Maybe it even may be the trigger to make people do some fine adjustments to their "branch" or portuguese.

Please let me know if there's anything you need me to change.

Cheers.

**Comment by projectdelphai** [comment]
Since you already created the pull request, that's good enough and any discussion can occur on there. I'll close this as a duplicate
