### ISSUE TITLE
Double click to create group

### ISSUE THREAD

**Issue by BlackenedGem** [projectdelphai/panorama-tab-groups#9]
The original tap groups addon (pre quantum) allows you to create a group by double clicking on the blank canvas as a nice Little QoL feature. Before you had to click the add button, then move the group to where you wanted. Now that you can drag tabs out of groups to create a group this is alleviated, but I still often find double clicking useful (for instance when extracting tabs from multiple groups to re-organise)

**Comment by projectdelphai** [comment]
easy enough to do! I'm working on a context menu to close groups since there's a pretty annoying bug revolving around that, but I'll take a look at this right after. Both of them should be done at end of day and uploaded to addons.mozilla.com tonight

**Comment by BlackenedGem** [comment]
Fantastic!

**Comment by projectdelphai** [comment]
Welp turns out context menus for specific elements are pretty hard so i'll just move to this for now LOL do you know if there was a shortcut to close a group? I was thinking about middle clicking

**Comment by projectdelphai** [comment]
There's already support for middle clicking to create a group and I didn't realize this as it wasn't documented anywhere, but it should now support double clicking to close a group. I didn't want to mess with any existing shortcuts but I can see if any changes to shortcuts should be done later. Should be updated on the addons site in the next couple hours tho. If you see 0.8.3, it's been updated.

**Comment by BlackenedGem** [comment]
Being able to close a group by double clicking is great and all, but we can already close a group using the X on the top right. Unfortunately middle clicking to create a group is rather problematic as most laptops don't have a middle mouse making it almost impossible to use that feature. And even on the desktop you'll find the middle mouse button is always the first to break.  

I don't know the issues with existing shortcuts, but while this issue has been closed the functionality of double clicking to create a group still isn't there.

**Comment by projectdelphai** [comment]
Makes sense to me, I'll switch them around

**Comment by projectdelphai** [comment]
This is done, I'll publish a new version by the end of the week at the latest
