### ISSUE TITLE
White flash when launching PTG

### ISSUE THREAD

**Issue by Pablo1107** [projectdelphai/panorama-tab-groups#90]
I have ShadowFox and others CSS rules in my userChrome.css to prevent white flashes in creating of new tab, loading a page, etc. This is currently working very well, but when I launch PTG in dark mode there is a split second of white screen (which also make my Vivaldifox frame white) before applying the theme.

As I know it's a recent feature added the option of starting in the selected theme option, maybe it's because by default it launches with the light theme, read the user option and toggle if necessary?

If this is the case I suggest two possible solutions:
 - Make dark theme the default when launch and toggle if light theme is selected.
 - Add a delay when launching PTG, waiting it has fully loaded before switch to that tab.

**Comment by vaxul** [comment]
This is something I stumbled myself. In the past I thought about your 2nd suggestion too. 
We could visually hide the body until the settings are applied. But this would leave the hole PTG page in a blank white until everything is loaded. It might change not much.
Ideally I'd like to prevent the light flash completely, but the rendering is all in the frontend Javascript. And we can't read the settings until the JS is loaded. Till then a white screen is not possible to prevent.

Currently an installation with a lot of tab groups takes quite a while. I hope for some major performance boosts in the future. 

If you have any idea or prototype, let me know.

**Comment by Pablo1107** [comment]
Thanks for the quick reply @vaxul 

I don't know how to code extensions for Firefox yet, but I'm looking forward in trying to contribute and learning in the process as I see this isn't a very complex proyect. 

If I encounter a way to fix this, I'll post a PR

**Comment by projectdelphai** [comment]
This should be fixed in the latest commits thanks to @aroskuski's work on optimizing the panorama view
