### ISSUE TITLE
Add translations for Send to Group/Refresh groups

### ISSUE THREAD

**Issue by projectdelphai** [projectdelphai/panorama-tab-groups#93]
https://github.com/projectdelphai/panorama-tab-groups/issues/74#issuecomment-465140010

**Comment by Slater91** [comment]
In Italian that would be:
"Send to group": "Invia al gruppo"
"Refresh groups": "Aggiorna gruppi"

**Comment by Beexx** [comment]
In French that would be:
"Send to group": "Envoyer au groupe"
"Refresh groups": "Actualiser les groupes" (or "Rafraîchir les groupes")

**Comment by projectdelphai** [comment]
I don't see an Italian language locale so not sure where to put this. French is done in fr_FR

**Comment by projectdelphai** [comment]
I don't see an Italian language locale so not sure where to put this. French is done in fr_FR

**Comment by projectdelphai** [comment]
Closed as no Italian locale to add to
