### ISSUE TITLE
Not sure if there import/export options works correctly

### ISSUE THREAD

**Issue by Neytrino-OnLine** [projectdelphai/panorama-tab-groups#94]
I created 3 groups and place several tabs in each of them,
https://cdn1.savepice.ru/uploads/2019/2/20/ed33dd0cbe714e415c0ba9b77ba44ecf-full.png
then I export settings:
https://yadi.sk/d/1KzR9G-TppLF6Q
Then import, and I get this:
https://cdn1.savepice.ru/uploads/2019/2/20/ec272ed7ed96f7a01aa5037b118b70ca-full.png
All tabs in one group, is it should work like this?

**Comment by vaxul** [comment]
Hi @Neytrino-OnLine , your screenshot are broken.
All tabs in one group is currently the fallback, if a group for a tab could be found/created.

**Comment by Neytrino-OnLine** [comment]
SCR1 https://flic.kr/p/RCP71c
SCR2 https://flic.kr/p/2e1kcM6

**Comment by sunnydavis** [comment]
Confirm the same problem happened to me too. (version 0.8.9)

**Comment by projectdelphai** [comment]
Need to sleep but narrowed down the commit that broke this issue to 9d3e53d

**Comment by projectdelphai** [comment]
Going to investigate tomorrow morning why it broke it and how to fix it
