### ISSUE TITLE
Send to Group navigates to end of tab strip

### ISSUE THREAD

**Issue by KamasamaK** [projectdelphai/panorama-tab-groups#95]
Thank you for this new feature! There are two annoyances I've found with it.

1. You have to focus off the tab before the move occurs. This is a fairly minor annoyance and possibly due to limitations of how Firefox works/the API.
2. The tab navigates to the end of the current tab strip before the move occurs. I am trying to move from my default set of a lot (read a few hundred) tabs so this is pretty annoying and time consuming to have to navigate back to where I left off each time.

**Comment by projectdelphai** [comment]
This should be fixed in the latest commit to master
